
comport: COM4
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1

VM: Y
VM-Version: potato

Mappings:
    ID1:
        Applications:
        VM: Input5
    ID2:
        Applications: 
        VM: Input6
    ID3:
        Applications: 
        VM: Input7 
    ID4:
        Applications: 
        VM: Output0
    ID5:
        Applications: 
    ID6:
        Applications: 
    ID7:
        Applications: 
    ID8:
        Applications: 
    ID9:
        Applications: 
    ID10:
        Applications: 
    ID11:
        Applications: 
    ID12:
        Applications: 
    ID13:
        Applications: 
    ID14:
        Applications: 
    ID15:
        Applications: 
    ID16:
        Applications: 