
comport: COM4
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1

Mappings:
    ID1:
        Applications: Discord.exe;plex.exe
    ID2:
        Applications: chrome.exe
    ID3:
        Applications: 
    ID4:
        Applications: 
    ID5:
        Applications: 
    ID6:
        Applications: 
    ID7:
        Applications: 
    ID8:
        Applications: 
    ID9:
        Applications: 
    ID10:
        Applications: 
    ID11:
        Applications: 
    ID12:
        Applications: 
    ID13:
        Applications: 
    ID14:
        Applications: 
    ID15:
        Applications: 
    ID16:
        Applications: 
