comport: COM3
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
VM: N
VM-Version: banana

Mappings:
  ID1:
    Applications: chrome.exe;Spotify.exe;firefox.exe
    VM: Input0;Input1
  ID2:
    Applications: cs2.exe;javaw.exe;RocketLeague.exe;Cyberpunk2077.exe;Stardew Valley.exe;Factorio.exe;master
    VM: Input1
  ID3:
    Applications: Plexamp.exe;Spotify.exe
    VM:
  ID4:
    Applications: chrome.exe;Plex.exe;firefox.exe;vlc.exe
    VM:
  ID5:
    Applications:
    VM:
