comport: COM6
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1

VM: N
VM-Version: banana

Mappings:
    ID1:
        Applications:
        VM: 
    ID2:
        Applications: 
        VM: 
    ID3:
        Applications: 
        VM: 
    ID4:
        Applications: 
        VM: 